### ISSUE TITLE
Add LLM settings to chat stage config

### ISSUE THREAD

**Issue by LeoLaugier** [PAIR-code/llm-mediation-experiments#12]
- [ ] Create and save LLM Mediator though its options
- Mediator ID
- model_name (as defined by the API, e.g. "text-bison@001")
- LLM API service
- prefix
- suffix
- [ ] scrolling menu to select existing Mediator IDs

**Comment by vivtsai** [comment]
FYI, added #51 to set up API connection and updated this issue so it's just for specifically adding the in-chat config.
