### ISSUE TITLE
Add free-form text to survey module

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#155]

**Comment by cjqian** [comment]
![Image](https://github.com/user-attachments/assets/67734c54-8bed-4764-bffb-6ceee83fb6ca)

**Comment by vivtsai** [comment]
https://github.com/PAIR-code/llm-mediation-experiments/commit/c5480afed905b00f78ced2fd72950fcd5d582216

https://github.com/PAIR-code/llm-mediation-experiments/commit/b36875c705bac439cd2532bb2b90f5cd2ded4e8a
