### ISSUE TITLE
Add default waiting stage to LAS

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#159]

**Comment by vivtsai** [comment]
Can `progress-stage-waiting` component be adapted for this? Or do you mean something else? @cjqian

**Comment by cjqian** [comment]
Thanks for the pointer, I'll have a look! I meant for this one particularly; I'd like when "add Lost at Sea stages" it automatically creates a divider and updates the experiment type.

**Comment by vivtsai** [comment]
Oh, I see—you mean lobby stage. No need to take a look then; I was just confused about what this meant
