### ISSUE TITLE
Add implicit reveal stage (to show results, solutions, and team score)

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#17]
In the vote reveal panel, display

1. Who was elected as the team leader
2. The final resulting task order
3. The correct task order (with an explanation or info icon popup?)
4. A scoring indicator (see appendix o

![Image](https://github.com/PAIR-code/llm-mediation-experiments/assets/4844633/5632a1c1-5f37-47ed-9b3c-14d9899de4c8)

f https://docs.google.com/document/d/11IJXf-tZVKZp592-MNM3hIj9Rft6cBYV7UcYFS9VJJc/)

**Comment by vivtsai** [comment]
Updated proposal (see components doc) for this implementation:

1. Add result/scoring configuration settings to relevant existing stages (e.g., leader election stage)
2. Add an *implicit stage* for displaying all reveals/results (automatically added to experiment if 1+ stages have results/scoring configured)

**Comment by vivtsai** [comment]
The Lit frontend has an MVP "reveal" stage, i.e., results preview for election (vote for leader) stage:

`lit/src/experiment-components/modules/election/election_reveal.ts`

Ideally, we want this election preview component, along with new components for Lost at Sea reveals, to be rendered inside a new implicit Reveal stage component.

Note that setting this up will involve:

(a) **adding implicit-ness**: cleaning up experiment_config and utils logic around adding the reveal stage (e.g., make sure exactly 1 reveal stage is present iff. at least one of the other stages has results configured)

(b) **showing multiple reveals**: updating (or replacing) the current RevealVoted stage in backend (which can only be tied to one VoteForLeader stage - instead, we'll want it to link to all stages with results). Actually, the fastest way to do this might be to ignore this backend field and instead select stages on the frontend (i.e., when rendering the new Reveal component, just check all the other stages to see which ones have results configured)?

**Comment by cjqian** [comment]
Updated design here: https://docs.google.com/document/d/1mQAhpm7rW1xWUhYFcjWHlKdZmOe12HWc0OZSeK6UIlk/edit?tab=t.0
