### ISSUE TITLE
Validate with UX designers that avatars are appropriate before public trials

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#20]

**Comment by vivtsai** [comment]
How were the current avatars chosen?

**Comment by vivtsai** [comment]
Update: In chat, we discussed switching to emoji avatars, e.g., 🙇🙇🏻...🙇🏿🙇‍♀️...🙇🏿‍♀️🙇‍♂️...🙇🏿‍♂️🙋...🙋🏿‍♂️...🧑‍🍼...👨🏿‍🍼

**Comment by vivtsai** [comment]
@cjqian can we close out this issue, or do these still need to be validated? (I'm planning on opening a new implementation issue for implementing the avatars.)

**Comment by cjqian** [comment]
Happy to close out for now, thank you!
