### ISSUE TITLE
Create data export (CSV/tabular data) for experiment analysis

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#24]
From the tech doc:

> For analysis by experiment: provide CSV/tabular data for data export.
> Flatten data. Every stage has its own set of columns.
> Principles: be able to replay the experiment

**Comment by vivtsai** [comment]
@cjqian What exactly do you have in mind for this? Could it basically be the current JSON download, but in column form? Or are we missing anything?

**Comment by cjqian** [comment]
Good question; I think current JSON is probably fine for now. Let's keep this in the backlog until we have our first batch of feedback from experimenters (e.g. Mael, Clementine).
