### ISSUE TITLE
Fix hosting local item assets

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#36]
As a temporary workaround, host online.

**Comment by vivtsai** [comment]
Could we host in Firebase storage?

**Comment by cjqian** [comment]
There was some issue about this (@LeoLaugier or @TiboX2021 may be able to explain further); you'll see that currently, we host on Github and then point to the raw user content URL 🙃

**Comment by TiboX2021** [comment]
We could use Firebase storage for static assets, but given the small amount of images we host, I find it overkill. This was an issue with the Angular app, we will have to see how to do it with the lit app (which might not require the rawgithubusercontent workaround). @vivtsai if you want, I can setup a Dockerfile for the lit frontend and test it for url prefixes (at EPFL we deploy the frontend on a generic domain with a url prefix, which is sometimes problematic for app that use relative static asset paths)

**Comment by vivtsai** [comment]
Ah, I see. Yes, if you're able to test, that would be great. Presumably if the favicon (the only stored image we have right now) works (or we can get it to work), we'll be able to similarly store the Lost at Sea images?
