### ISSUE TITLE
Lit app: textarea newline exception

### ISSUE THREAD

**Issue by TiboX2021** [PAIR-code/llm-mediation-experiments#44]
When entering a newline in a lit `pr-textarea` from the pair-components, I get this error:

![image](https://github.com/PAIR-code/llm-mediation-experiments/assets/87866393/d1c1c828-1e01-41b8-aaa8-6d72b879b273)

It might have to do with a missing `window.requestAnimationFrame` to delay resizing.

Reproduction steps:
- Find a text input (the underlying implementation is the `pr-textaera` component.
- Press `Enter`
- The error should pop up and cover the screen

Example: with the participant login textarea
![image](https://github.com/PAIR-code/llm-mediation-experiments/assets/87866393/2f775037-4e93-4ba7-a43e-6c903fe39b10)

**Comment by vivtsai** [comment]
Haven't been able to repro this. Is this still an issue on your end?

**Comment by cjqian** [comment]
@TiboX2021 Can you verify the reproduction steps and/or close this out?

**Comment by TiboX2021** [comment]
I added reproduction steps. You can try this out on the login page, when pressing Enter in a text input.

**Comment by vivtsai** [comment]
I tried the repro steps but didn't see anything. We could still add a resize delay as suggested if it's still an issue?

**Comment by vivtsai** [comment]
Alternatively, feel free to swap in https://material-web.dev/components/text-field/ if that will work better, e.g., no resizing errors as could use regular text input instead of textarea. (The main reason we built the currently used pr-textarea is for specific components like chat message bubbles where Material Web Components don't have the behavior/style we need—which isn't the case for login screen.)

**Comment by TiboX2021** [comment]
I have tested it again, it seems to occur only with firefox, not chrome. I will see if I can fix quickly on firefox.

**Comment by TiboX2021** [comment]
I think that they are minor errors relayed by the webpack dev overlay, because they are not logged to the console. For some reason this specific error is only triggered in firefox and not in chrome.

I can disable runtime errors display in the webpack config like this:
![image](https://github.com/PAIR-code/llm-mediation-experiments/assets/87866393/48adaabb-8360-42c6-92e9-5322fdfff7c8)

If don't think we will miss out on errors, as the important ones will be logged to the console anyway. If it is ok with you I can push this to main.

**Comment by vivtsai** [comment]
That's fine with me!
