### ISSUE TITLE
Add version info to deployment builds

### ISSUE THREAD

**Issue by vivtsai** [PAIR-code/llm-mediation-experiments#69]
Somewhere in the frontend UI (e.g., info tooltip? settings page?), show the current version of the app (so that it's easy to tell if two deployments are on the same version).

For version info, use `.git/` to include GitHub branch ref, commit, and whether or not there are unstaged changes --> all three should be enough to compare versions?

**Comment by GnRlLeclerc** [comment]
Added to the settings page

![image](https://github.com/PAIR-code/llm-mediation-experiments/assets/87866393/208b974a-802e-4e28-a771-d14f2905bf1e)
