### ISSUE TITLE
Add script to generate fake experimenters with google.com as a provider

### ISSUE THREAD

**Issue by TiboX2021** [PAIR-code/llm-mediation-experiments#9]
Experimenters authenticate through the google.com popup (which also allows other auth providers). We should create a script to generate fake experimenters with auth providers in order to facilitate development and testing.

However, it seems that creating fake users with an auth provider programmatically is not easy (I did not find how to do it).

**Comment by iislucas** [comment]
I think you can do it with https://firebase.google.com/docs/cli/auth using a command like: 

```
$ firebase auth:export ACCOUNT_FILE --format=FILE_FORMAT
```

I think you can just add some google account email's into the account file and it'll use it... (But I haven't tried this)... did you already try it?

**Comment by TiboX2021** [comment]
I found a way to do it with emulators: https://github.com/firebase/firebase-tools/pull/2955
I will add a simple dump for 2 auth users (experimenter and not experimenter) which will be loaded on startup

**Comment by iislucas** [comment]
perfect!
