### ISSUE TITLE
Allow data downloads/analysis for experiments (to ensure we are collecting the right data)

### ISSUE THREAD

**Issue by vivtsai** [PAIR-code/llm-mediation-experiments#92]
Added this based on internal chat discussion with @cjqian.

**Comment by cjqian** [comment]
Marking #24 as duplicate. Might be worth sending some data to experimenters (e.g. Mael, Clementine) to validate as well!

**Comment by cjqian** [comment]
Two things that would be useful here:

* A JSON dump (or dump per experiment) with all metadata from the experiment and participant 
* A payout CSV with each participant and how much money they've earned
