### ISSUE TITLE
“Copy link” from experiment removes the `/palabrate` from EPFL link

### ISSUE THREAD

**Issue by vivtsai** [PAIR-code/llm-mediation-experiments#95]

**Comment by GnRlLeclerc** [comment]
I don't think there is a builtin way to detect subroutes like `palabrate`, however the url looks like `https://modemos.epfl.ch/palabrate/#/experimenter` so we could take the whole url and split it manually at `#`

**Comment by cjqian** [comment]
Yes, fixed in https://github.com/PAIR-code/llm-mediation-experiments/commit/4660580384df621f28fda28d9aa447a93845a70a
